# Generated by Django 3.0.8 on 2020-07-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='remark',
            new_name='filename',
        ),
    ]
